### ISSUE TITLE
Make Pkg.test() work

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/MySQL.jl#3]
Currently, Pkg.test() fails. Not sure what a good way is to deal with the user/pass for automated testing.

As soon as we open source this, let's also plug it into Travis.

**Comment by ViralBShah** [comment]
I think it would be good to have some instructions on how to configure mysql if you want to test - perhaps the password needs to be root or some such thing.

How difficult would it be to set up travis on this?

**Comment by nkottary** [comment]
Travis is setup now. It is set to run for julia release, nightly, 0.3 and 0.4.

**Comment by ViralBShah** [comment]
Are we getting a few greens on Travis? If so, we can close this one.

**Comment by nkottary** [comment]
Yes, the tests are successful on Travis.

On 22 September 2015 at 17:09, Viral B. Shah <notifications@github.com>
wrote:

> Are we getting a few greens on Travis? If so, we can close this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaComputing/MySQL.jl/issues/3#issuecomment-142261778>
> .
>



-- 
Nishanth H. Kottary

**Comment by ViralBShah** [comment]
Tests are failing on nightly. Perhaps disable that if that is not supported? Would be nice to have a green badge.

**Comment by nkottary** [comment]
Nightly builds disabled in ce43d2deb78407bdfc0c87c9a6e4a6f6ad71daae

**Comment by ViralBShah** [comment]
Please close if issue is fixed.
